### PR TITLE
Console fix

### LINKED ISSUE #22: Exception raised from Parser.HelpInfo
**Describe the bug**
If the method `Parser.HelpInfo` is called outside a real console application (e.g. the output is redirected) an exception is raised because there isn't a real underlying device.

**Expected behavior**
Trap the exception or identify the unavailable device.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: all
 - Version: all

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by masesdevelopers**
## Description
Added try-catch to avoid exception raise, default width set to 80.

## Related Issue

closed #22 

## How Has This Been Tested?

Not tested

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

File: src/CLIParser/CLIParser.cs [hunk 1]
```diff
@@ -681,7 +681,12 @@ public int PaddingFromArguments()
         /// <returns>A <see cref="string"/> with help information</returns>
         public string HelpInfo(int? width = null)
         {
-            int newWidth = Console.WindowWidth;
+            int newWidth = 80; // set a default
```
Comment (mariomastrodicasa) [inline src/CLIParser/CLIParser.cs:684]: Instead of set the default here, add something can be set from the library user

**Review by mariomastrodicasa — APPROVED** [review]
